### ISSUE TITLE
pytest-xdist crashes tests

### ISSUE THREAD

**Issue by mfreibergs** [microsoft/playwright-pytest#100]
Running tests with pytest-xdist in parallel doesn't correctly clean up the test-results folder and crashes the tests. Don't know if this can be fixed from playwright-pytest or pytest-xdist instead

**Comment by mfreibergs** [comment]
```py
// conftest.py
import shutil
import os

output_dir = "test-results"

def pytest_configure():
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
```
Adding this fixes the current problem. There probably is a better solution.

**Comment by mxschmitt** [comment]
Should be fixed by https://github.com/microsoft/playwright-pytest/pull/97
