### ISSUE TITLE
[Feature] Implement retries and on-first-retry for assets

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-pytest#130]
We could probably rely on https://pypi.org/project/pytest-rerunfailures/ and use it's count in order to generate the artifacts.

**Comment by logicalpath** [comment]
Hello, I'm curious if this enhancement is on the roadmap for the near future?

Thanks,
Eddie

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-pytest/issues/210
