### ISSUE TITLE
Default browser is not 'all browsers'

### ISSUE THREAD

**Issue by QuLogic** [microsoft/playwright-pytest#132]
The [CLI arguments in the docs](https://playwright.dev/python/docs/test-runners#cli-arguments) state:

* `--browser`: Run tests in a different browser `chromium`, `firefox`, or `webkit`. It can be specified multiple times (default: **all browsers**).

However, when I run plain `pytest`, I do not see _all_ browsers running, only Chromium.

**Comment by samamorgan** [comment]
Seconded, same behavior for me. I have to specify all browsers individually in my `pyproject.toml` test settings to get the documented behavior.
