### ISSUE TITLE
--screenshot=on does not take screenshot if context is defined in conftest.py

### ISSUE THREAD

**Issue by soprano8086** [microsoft/playwright-pytest#139]
Hi, 
I am new to Playwright and I am trying to build a framework using playwright and pytest-bdd. I want to take screenshot when test fails but can't make that work. Below is simplified steps I tried, without the bdd.  I am not sure this is defect or something I should put in conftest.py 
 
**environment**
```
playwright           1.27.1
pytest-playwright    0.3.0
pytest               7.2.0
pytest-base-url      2.0.0
pytest-bdd           6.0.1
```

**step1: tests/demo.py**
The test will fail
```
from playwright.sync_api import Page
def test01_login(page: Page):
    page.goto('https://www.google.com/')
    page.wait_for_selector('#usernameForm1', timeout=200)
```
**step2: run test**
```
pytest -sv tests/demo.py --screenshot=on
```
`test-results` is created and screenshot is generated. 

**step3: conftest.py**
```
import pytest
from playwright.sync_api import Browser

@pytest.fixture(scope="session")
def context(browser: Browser):
    context = browser.new_context(ignore_https_errors=True)
    yield context
    context.close()
```
**step4: run test again**
`test-results` won't be created. If it exists it will be removed. 

**step5: test/demo2.py**
using context
```
from playwright.sync_api import Playwright, sync_playwright

def test01_login(context):
    page = context.new_page()
    page.goto('https://www.google.com/')
    page.wait_for_selector('#usernameForm1', timeout=200)
```
**step6: run demo2**
no screenshot is generated. 
```
rm -fr test-results
pytest -sv tests/demo2.py --screenshot=on
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-pytest/issues/111

**Comment by TonyKorolev** [comment]
Hello! Is there any progress on this issue? When is it planned to release adding screenshots with new_context?
