### ISSUE TITLE
[BUG] Plugin not compatible with SeleniumBase: conflicting option string: --browser

### ISSUE THREAD

**Issue by sumitmahajan** [microsoft/playwright-pytest#14]
![image](https://user-images.githubusercontent.com/29740479/95115188-113e4a00-0713-11eb-838a-13a3d830a4be.png)
I can put in a fix by changing the --browser option tp --pwbrowser. Let me know. I made required changes to couple of places and is working now.

**Comment by mxschmitt** [comment]
Which other pytest plugins are you using? Are you using pytest-selenium?

**Comment by sumitmahajan** [comment]
Yes and a couple of others. I guess we can use a virtual environment but
imho --browser is too common as an option parameter. But thanks for the
quick response.

Best Regards
Sumit Mahajan

**Comment by mxschmitt** [comment]
Could you provide us a list of plugins which you use? pytest-selenium seem not to cause a CLI argument clash.

**Comment by sumitmahajan** [comment]
![image](https://user-images.githubusercontent.com/29740479/95128370-52405980-0727-11eb-8e91-77364b4ddbe5.png)
Found the rootcause. It's this library https://github.com/seleniumbase/SeleniumBase

**Comment by mxschmitt** [comment]
Had a discussion with pfeldman offline. It's not considered as a bug since normally the users won't use SeleniumBase in combination with playwright-pytest.

**Comment by zhonghai9967** [comment]
I am testing playwright, seleniumbase,I found a temporary solution:
Open with a text editor "c:\python38\Lib\site-packages\pytest_playwright\pytest_playwright.py"
Find line 175，Modify "--browser" to "--browserr"

When using pytest-playwright: 
pytest my.py --browserr firefox

**Comment by zhonghai9967** [comment]
playwright-python运行网页脚本的速度比seleniumbase要快一些。
