### ISSUE TITLE
[Question]: Why the fixture is not session scope for the page function at pytest_playwright.py in the source code 

### ISSUE THREAD

**Issue by AllenLuosong** [microsoft/playwright-pytest#142]
like the below code at line 278 of pytest_playwright.py

```
@pytest.fixture
def page(context: BrowserContext) -> Generator[Page, None, None]:
    page = context.new_page()
    yield page
```

I wonder why the scope is not session, as my scenario is want the page open all the time while my csaes run.

here is my case, and I hope it open one page to run two case, not open two pages to run two case 

```
def test_homepage(page: Page):
    page.goto(page, url="https://playwright.dev/")
    
    # Expect a title "to contain" a substring.
    expect(page).to_have_title(re.compile("Playwright"))
    page.wait_for_timeout(3000)

def test_start_page(page: Page):
    page_element_click(page, selector='text="Get started"')
    page.wait_for_timeout(3000)`
```

**Comment by mxschmitt** [comment]
The Pytest plugin for Playwright applies the Playwright best practises which include having a new context (which gives you also a new page) per each test. This is to ensure the tests are isolated between each other and do not infer with other tests when a single test is failing.

In your case we recommend a single long test or [test steps](https://smarie.github.io/python-pytest-steps/).
