### ISSUE TITLE
docs: add example to the "Customizing fixture options" section (e.g. for browser_context_args)

### ISSUE THREAD

**Issue by qupfer** [microsoft/playwright-pytest#15]
Hi, I'm complete new to pytest/playwright and have only small experiences with pytohn. 
That means, my question is propably more a general syntax/understanding problem as a playwright issue. But hopefully somebody wants to help anyway :-) 

I want to create some tests for a site with a self-signed certificate, so I need to pass the "ignoreHTTPSErrors=True" option.
At the moment, I use this (as a workaround):

```
def test_invalid_user_login(browser):
    context=browser.newContext(ignoreHTTPSErrors=True)
    page=context.newPage()
    login(page,username="invaliduser",password="validpassword")
```
This works, but would require too redundant line per test. Not a big problem, but I think not the best solution. 

From the README.MD, I got this information:

> browser_context_args: Override the options for browser.newContext(). It should return a Dict.

Which sound exactly what I need. But all ways I tried, I got still an certificate error --> ignoreHTTPSErrors=True is not used.
`FAILED test_1.py::test_normal_login[chromium] - playwright.helper.Error: net::ERR_CERT_AUTHORITY_INVALID at http://10.10.10.10/
`
Can give somebody me a correct example, how to set/use this fixture?

Thanks a lot

**Comment by mxschmitt** [comment]
Hi, you can create a `conftest.py` in your end-to-end test directory with the following content:

```py
      import pytest
        @pytest.fixture(scope="session")
        def browser_context_args(request):
            return {"ignoreHTTPSErrors": True}
```

In your test then you can have:

```py
def test_invalid_user_login(page):
    login(page,username="invaliduser",password="validpassword")
    # custom logic
```

Maybe we should document it how fixtures work in general with the `conftest.py` usage.

**Comment by qupfer** [comment]
Thanks, that helps a lot.

**Comment by arjun27** [comment]
Thanks! I'll re-frame this to update the docs with this example

**Comment by algot** [comment]
> Maybe we should document it how fixtures work in general with the `conftest.py` usage.
It would be very helpful because it's not clear even if I was familiar with pytest fixtures

**Comment by mxschmitt** [comment]
@algot that should work:

```py
import pytest
@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {**browser_type_launch_args, "args": ["--start-maximized"]}
```

**Comment by algot** [comment]
@mxschmitt It works - browser opens maximized but viewport still have default size.
Is it expected behavior and I have to set viewport explicitly?
