### ISSUE TITLE
[QUESTION] Can't install pytest-playwright 0.3.0

### ISSUE THREAD

**Issue by metju29** [microsoft/playwright-pytest#152]
When I try to install pytest-playwright 0.3.0 from a local repository I get an error:

ERROR: Could not find a version that satisfies the requirement charset-normalizer<3,>=2 (from requests) (from versions: 3.0.1)
ERROR: No matching distribution found for charset-normalizer<3,>=2

Is it possible upgrade charset-normalizer to charset-normalizer 3.0.1?

**Comment by mxschmitt** [comment]
Can you provide a requirements.txt file? Or a small repro? Maybe there is some dependency which conflicts.

**Comment by metju29** [comment]
requirements.txt:
`attrs @ file:///xxx/packages/attrs-22.1.0-py2.py3-none-any.whl
certifi @ file:///xxx/packages/certifi-2022.12.7-py3-none-any.whl
charset-normalizer @ file:///xxx/packages/charset_normalizer-3.0.1-cp311-cp311-win_amd64.whl
colorama @ file:///xxx/packages/colorama-0.4.6-py2.py3-none-any.whl
execnet @ file:///xxx/packages/execnet-1.9.0-py2.py3-none-any.whl
greenlet @ file:///xxx/packages/greenlet-2.0.1-cp311-cp311-win_amd64.whl
idna @ file:///xxx/packages/idna-3.4-py3-none-any.whl
iniconfig @ file:///xxx/packages/iniconfig-1.1.1-py2.py3-none-any.whl
packaging @ file:///xxx/packages/packaging-22.0-py3-none-any.whl
playwright @ file:///xxx/packages/playwright-1.30.0-py3-none-win_amd64.whl
pluggy @ file:///xxx/packages/pluggy-1.0.0-py2.py3-none-any.whl
pyee @ file:///xxx/packages/pyee-9.0.4-py2.py3-none-any.whl
pyparsing @ file:///xxx/packages/pyparsing-3.0.9-py3-none-any.whl
pytest @ file:///xxx/packages/pytest-7.2.0-py3-none-any.whl
pytest-xdist @ file:///xxx/packages/pytest_xdist-3.1.0-py3-none-any.whl
python-slugify @ file:///xxx/packages/python_slugify-7.0.0-py2.py3-none-any.whl
text-unidecode @ file:///xxx/packages/text_unidecode-1.3-py2.py3-none-any.whl
typing_extensions @ file:///xxx/packages/typing_extensions-4.4.0-py3-none-any.whl
urllib3 @ file:///xxx/packages/urllib3-1.26.14-py2.py3-none-any.whl`

**Comment by mxschmitt** [comment]
I think the easiest if you use https://github.com/tox-dev/pipdeptree to find out which two dependencies depend on `charset-normalizer` to figure out the bad behaving one. Since a normal stock installation works, I'm pretty sure its not an issue on our side.

**Comment by mxschmitt** [comment]
Closing since its stale, please re-file for further questions.
