### ISSUE TITLE
Traces don't contain the test name

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright-pytest#156]
The traces created by the pytest plug don't add the test/node name to the trace:
![image](https://user-images.githubusercontent.com/20302512/225650469-62e102e3-b119-4828-8edd-34d3ccb81679.png)

Is this returning an empty string? ```name=slugify(request.node.nodeid),```

**Comment by mxschmitt** [comment]
Thanks for reporting the bug. I created https://github.com/microsoft/playwright-pytest/pull/157 with a fix for it.
