### ISSUE TITLE
Error: ENAMETOOLONG: name too long    （goto url too long occure error） triggerUncaughtException(err, true /* fromPromise */);

### ISSUE THREAD

**Issue by dreamhighqiu** [microsoft/playwright-pytest#164]
cases/monkey/playable/test_playable_monkey.py::TestMonkeyPage::test_pl_1_video[chromium-https://mmp-cdn.rayjump.com/qatask/t42726/v1/google_zh-tw_ToonBlastfulljellyjellygoal_91FODk6qo_an_320x480/google_zh-tw_ToonBlastfulljellyjellygoal_91FODk6qo_an_320x480.html] node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENAMETOOLONG: name too long, open '/tmp/playwright-artifacts-DH6Uka/cases-monkey-playable-test-playable-monkey-py-testmonkeypage-test-pl-1-video-chromium-https-mmp-cdn-rayjump-com-qatask-t42726-v1-google-zh-tw-toonblastfulljellyjellygoal-91fodk6qo-an-320x480-google-zh-tw-toonblastfulljellyjellygoal-91fodk6qo-an-320x480-html.network'] {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/tmp/playwright-artifacts-DH6Uka/cases-monkey-playable-test-playable-monkey-py-testmonkeypage-test-pl-1-video-chromium-https-mmp-cdn-rayjump-com-qatask-t42726-v1-google-zh-tw-toonblastfulljellyjellygoal-91fodk6qo-an-320x480-google-zh-tw-toonblastfulljellyjellygoal-91fodk6qo-an-320x480-html.network'
}

Node.js v18.15.0
ERROR

**Comment by mxschmitt** [comment]
Could you provide us a reproduction for how your are getting this error? Do you manually start tracing? Do you have a long test name or do you parameterise your tests?
