### ISSUE TITLE
Inside pytest_playwright plugin browser_context_args() fixture is session scoped, but should be function scoped.

### ISSUE THREAD

**Issue by RomanLeca** [microsoft/playwright-pytest#179]
### System info
- Playwright Version: [v1.35]
- Operating System: [macOS 13.4]
- Browser: [All]
- Other info:
Inside pytest_playwright plugin code, the fixture [browser_context_args is session scoped](https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py#L172)

This presents a complication when trying to orchestrate different tests running on different context settings. E.g. different emulated devices, resolutions, etc.

I have tried adding capabilities to this fixture in conftest.py like so and it works
### Source code
```python
@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    """
    This fixture will add capabilities to the original browser_context_args fixture from the pytest_playwright plugin
    """
    browser_context_args.setdefault("http_credentials", {"username": AUTH_USERNAME, "password": AUTH_PASSWORD})

    return browser_context_args
```
but the problem occurs when changing the scope to "function" so it is test dependent, not session wide.
The credentials simply do not get picked up.

**Expected**

Browser context args should be context dependent, hence function scoped

**Actual**

Broser context args are session scoped in the plugin.

**Workaround**
I copied the context fixture inside conftest, which allows me to control customisations prior to [this line](https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py#L239) but this involves handling non-recommended imports for functions like _build_artifact_test_folder() and I am not proud of it :)

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file if you are still encountering issues.
