### ISSUE TITLE
Change locale without launching a persistent contex

### ISSUE THREAD

**Issue by 4ydan** [microsoft/playwright-pytest#180]
I have looked a bit around in the docu and in some issues.
I am having the problem setting a locale across all my contexts. When I use `launch_persistent_context` it removes the nice folder names when recording video files.

Is there a nice way to just change the locale or not override everything else?

This is what I have
```
@pytest.fixture(scope="session")
def context(
    browser_type: BrowserType,
    browser_type_launch_args: Dict,
    browser_context_args: Dict
):
    context = browser_type.launch_persistent_context(
        user_data_dir="./data",
        **{
            **browser_type_launch_args,
            **browser_context_args,
            "locale": "de-DE",
            "record_video_dir": "./test-results"
        })
    yield context
    context.close()
```

**Comment by mxschmitt** [comment]
Whats the reason you are using launch_persistent_context? If you want to set a custom locale, you can do it like shown here if you replace viewport with locale: https://playwright.dev/python/docs/test-runners#use-custom-viewport-size

**Comment by 4ydan** [comment]
I understand now, thank you.
