### ISSUE TITLE
[pylint] redefined-outer-name error using fixture exampled

### ISSUE THREAD

**Issue by qupfer** [microsoft/playwright-pytest#19]
Hi, it's me again :-)

I used the example about disabling HTTPS checks and it works great, but I think there may be an issue which can become a bug in more complex environments. 

Whats from README.MD
```python
import pytest

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "ignoreHTTPSErrors": True
    }
```
and whats from https://docs.pytest.org/en/latest/reference.html#pytest-fixture:

> name – The name of the fixture. This defaults to the name of the decorated function. If a fixture is used in the same module in which it is defined, the function name of the fixture will be shadowed by the function arg that requests the fixture; one way to resolve this is to name the decorated function fixture_<fixturename> and then use @pytest.fixture(name='<fixturename>').

I can't judge if this may become a problem or not, but at least pylint is complaining about that.
Maybe the example should get a node about that or changed.

```python
@pytest.fixture(name='browser_context_args', scope="session")
def fixture_browser_context_args(browser_context_args):
    """disable cert check"""
    return {
        **browser_context_args,
        "ignoreHTTPSErrors": True
        }
```

**Comment by mxschmitt** [comment]
Hi, I don't think this will lead to issues. The main intention there is that we internally in playwright-pytest have the fixture also defined. So we are overwriting the already defined fixture and extending it with the ignore HTTPSErrors option.

**Comment by qupfer** [comment]
Thanks, sounds good.
I changed the title, so thats easier to found if anybody had the same lint error
