### ISSUE TITLE
Coverage support

### ISSUE THREAD

**Issue by pamelafox** [microsoft/playwright-pytest#190]
I am wondering if there's any possibility of seeing coverage for the frontend JS files when we run pytest-playwright. I assume not, but want to confirm before I write off the possibility.

**Comment by mxschmitt** [comment]
There is no out of the box solution. It can be done in the user land like here in e.g. JS: https://github.com/mxschmitt/playwright-test-coverage.

Folding into https://github.com/microsoft/playwright/issues/9208.
