### ISSUE TITLE
 playwright._impl._api_types.Error: net::ERR_CONNECTION_TIMED_OUT at https://www.google.com

### ISSUE THREAD

**Issue by crazy-yuzhao** [microsoft/playwright-pytest#196]
pytest.ini
[pytest]
base_url = https://www.google.com

conftest.py
@pytest.fixture(scope="session")
def page_session(page: Page):
    page.goto("/")

def test_a(page_session):
    print(f'aaaaa')

run result

    @pytest.fixture(scope="session")
    def page_session(page: Page):
>       page.goto("/")

E       playwright._impl._api_types.Error: net::ERR_CONNECTION_TIMED_OUT at https://www.google.com
E       =========================== logs ===========================
E       navigating to "https://www.google.com/", waiting until "load"
E       ============================================================

Why does this error sometimes appear when executing a use case? 
After running it 10 times, it may appear two or three times.

**Comment by crazy-yuzhao** [comment]
page = <Page url= ' about: bLank'>

**Comment by crazy-yuzhao** [comment]
E ======== page = <Page url= ' about: bLank'>

**Comment by crazy-yuzhao** [comment]
Page url= ' about: bLank'

**Comment by mxschmitt** [comment]
Looks like there is a timeout when reaching google.com. If google.com is an example URL in this case it might be related that the website you are navigating to is not reachable, offline etc.
