### ISSUE TITLE
[BUG] device emulation is not possible

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-pytest#20]
Hi all!
How can I start tests, when I want to run it as it's browser on IPhone? Something like, but in the fixture:
```
 iphone_11 = p.devices['iPhone 11 Pro']
    browser = p.webkit.launch(headless=False)
    context = browser.newContext(
        **iphone_11,
        locale='en-US',
        geolocation={ 'longitude': 12.492507, 'latitude': 41.889938 },
        permissions=['geolocation']
    )
```
As I read in documentation, it's possible only to specify browser.

**Comment by mxschmitt** [comment]
@akozyreva I've fixed it and published a new version of playwright-pytest (0.0.8). A full example how to use it you can see here: https://github.com/microsoft/playwright-pytest#device-emulation
