### ISSUE TITLE
Request: `async` support

### ISSUE THREAD

**Issue by jamesbraza** [microsoft/playwright-pytest#201]
From https://github.com/microsoft/playwright-pytest/blob/v0.4.3/pytest_playwright/pytest_playwright.py#L23-L31, it's clear only synchronous usage is supported here (there are no `async_api` imports).

Thus, `async` workflows are not well supported by `playwright-pytest`. This request is to support asynchronous usage.

---

Workaround

https://github.com/m9810223/playwright-async-pytest exists, but it's currently pinned to an older version of `pytest-playwright`: https://github.com/m9810223/playwright-async-pytest/blob/v0.3.0/pyproject.toml#L4

**Comment by jamesbraza** [comment]
Actually, this is a duplicate of https://github.com/microsoft/playwright-pytest/issues/74

**Comment by mxschmitt** [comment]
Note: I was working on it a while ago but struggled implementing the requirements we had: https://github.com/microsoft/playwright-pytest/pull/184#issuecomment-1902081523

**Comment by jamesbraza** [comment]
I added some comments, feel free to bounce ideas off me if that helps

**Comment by m9810223** [comment]
I just loosen the version of `pytest-playwright` in https://github.com/m9810223/playwright-async-pytest.
