### ISSUE TITLE
[FEATURE] Support pytest 8.x

### ISSUE THREAD

**Issue by MShekow** [microsoft/playwright-pytest#202]
Projects that stay on the latest an greatest dependencies no longer work. pip complains:

```
ERROR: Cannot install -r requirements.txt (line 10) and pytest==8.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pytest==8.0.0
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    pytest-playwright 0.4.3 depends on pytest<8.0.0 and >=6.2.4
```

Pytest 8 has been released yesterday, see https://docs.pytest.org/en/stable/changelog.html#pytest-8-0-0-2024-01-27

**Comment by mxschmitt** [comment]
Currently blocked by https://github.com/pytest-dev/pytest-base-url/issues/41.

**Comment by MShekow** [comment]
Thanks for fixing the issue so quickly. Do you have any ETA of a new release of playwright-pytest on pytest? It's not urgent for me or anything, I'm just curios.

**Comment by mxschmitt** [comment]
I'll release right now!
