### ISSUE TITLE
Allow extending playwright capabilities

### ISSUE THREAD

**Issue by Formartha** [microsoft/playwright-pytest#213]
Hi,

The plugin is written without hookspec entry points, and as a result, it’s hard to modify it’s data.

for example, I want to implement saving data of tests to DB. It’s impossible without it.

I can suggest myself to work on it, if you’d like, else, I can fork the project and do it.

I saw the limitation in the source code of Playwright and I would love to help there as well.

Is that an option?

Thanks,
Mor

**Comment by mxschmitt** [comment]
When would you like to save the data to the DB? Maybe its already possible as of today, since Pytest's fixture ecosystem is very flexible in terms of when you want to execute something.

Would it be possible to provide us a some code as an example?
