### ISSUE TITLE
Move creation of artifacts_folder into a fixture

### ISSUE THREAD

**Issue by m-reichle** [microsoft/playwright-pytest#222]
Hi! 

I'm running a mixture of Playwright and regular tests using pytest-xdist and am getting a lot of  warnings like this one: `ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/playwright-pytest-n3merlqy'>`

I've looked into the issue and from what I can make out, because of the way the artifacts_folder is created in https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py#L54, there is a temporary directory created for every worker and the control process, since they all touch pytest_playwright.py, but only those directories are properly removed again, that were created by a worker that happened to actually run a Playwright test. 

Same when I run a non-Playwright test without using xdist. 

I think the artifacts folder might be handled better with some sort of tmp_path factory fixture.

**Comment by m-reichle** [comment]
Wow, that was lightning fast! Thank you very much!

**Comment by mxschmitt** [comment]
This should be fixed in v0.5.0: https://pypi.org/project/pytest-playwright/
