### ISSUE TITLE
Setup proxy without losing pytest arguments

### ISSUE THREAD

**Issue by aklajnert** [microsoft/playwright-pytest#228]
I need to set some arguments for browser and the page, one of the most important is proxy settings. I've managed to do that with the following code:
```python
@pytest.fixture()
def page(playwright, pytestconfig):
    headed = pytestconfig.getoption("--headed")
    browser = playwright.chromium.launch(proxy=proxy, headless=not headed)

    page = browser.new_page(ignore_https_errors=True, extra_http_headers=auth_headers, proxy=proxy)

    yield page

    page.close()
```

This code, however, has one big flaw. I have lost support for command-line arguments. I can't enable tracing from the command line without rewriting (or copying) the code responsible for enabling it, and I really care about these features.

I tried to use `browser` fixture, but it doesn't seem to be able to set proxy on Windows:
```python
@pytest.fixture()
def page(browser):
    page = browser.new_page(ignore_https_errors=True, extra_http_headers=auth_headers, proxy=proxy)

    yield page

    page.close()
```

This code returns a following error:
> playwright._impl._errors.Error: Browser.new_page: Browser needs to be launched with the global proxy. If all contexts override the proxy, global proxy will be never used and can be any string, for example "launch({ proxy: { server: 'http://per-context' } })"

Is there a way to pass the proxy into `launch()` method without calling it directly?

**Comment by mxschmitt** [comment]
If you put this into your conftest.py it should work:

```python
import pytest

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "ignore_https_errors": True,
        "extra_http_headers": {},
        "proxy": {},
    }

@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {
        ** browser_type_launch_args,
        "proxy": "..."
    }
```

**Comment by aklajnert** [comment]
It does work, thank you!
