### ISSUE TITLE
How to reduce the default browser timeout?

### ISSUE THREAD

**Issue by davidbgk** [microsoft/playwright-pytest#23]
I tried a couple of things in my `conftest.py` file like:

```python
import pytest


@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    seconds = 2
    return {**browser_type_launch_args, "timeout": seconds * 1000}
```

But it doesn't look to be effective, I'm probably missing something, even reading the source code.

My intended goal is to fail test faster than the default 30 seconds to wait for a selector.

**Comment by mxschmitt** [comment]
Hi, it's not yet possible to set a global timeout with Playwright over the context (upstream limitation).

but you can overwrite the context and something like that in your `conftest.py` should work:

```py
@pytest.fixture
def context(context):
    context.setDefaultTimeout(5 * 1000)
    yield context
```

**Comment by mxschmitt** [comment]
Closed because of inactivity. Feel free to reopen or create an upstream feature request if the issue is still persistent.

**Comment by davidbgk** [comment]
Thank you @mxschmitt, I finally tried it and I got this error with launching my tests now:

```
_______________________________________________ ERROR at setup of test_click_on_french_tab ________________________________________________

launch_browser = <function launch_browser.<locals>.launch at 0x1035fc940>

    @pytest.fixture(scope="session")
    def browser(launch_browser: Callable[[], Browser]) -> Generator[Browser, None, None]:
>       browser = launch_browser()

venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:120: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

kwargs = {}, headful_option = False, launch_options = {}

    def launch(**kwargs: Dict[Any, Any]) -> Browser:
        headful_option = pytestconfig.getoption("--headful")
        launch_options = {**browser_type_launch_args, **kwargs}
        if headful_option:
            launch_options["headless"] = False
>       browser = getattr(playwright, browser_name).launch(**launch_options)
E       TypeError: getattr(): attribute name must be string

venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:112: TypeError
```

This is not anymore an problem related to the timeout but more on the way you can modify the context.

I can create a new issue for that but this is a good way to reproduce.

**Comment by vhoang1102** [comment]
For one who's looking for the correct setting, add the codes below to conftest.py:

`@pytest.fixture
def context(context):
    context.set_default_timeout(60000)
    yield context`
