### ISSUE TITLE
[Question] How to generate junit.xml without BrowserType in name

### ISSUE THREAD

**Issue by EldoradoEU** [microsoft/playwright-pytest#251]
Hi,

How can I generate JUnit .xml with the same name as test case, without BrowserType or parameter in name.
e.g.
actual:
![Image](https://github.com/user-attachments/assets/260dad77-afc2-42f1-939a-c8ee8305cd5e)

expected:
![Image](https://github.com/user-attachments/assets/dfccb9ae-65e5-43dd-98f0-38b95f821076)

Motivation:

Our test management tool based on date from .xml, so we need the same format in .xml as required to execute test case.
e.g.
classname="test_example"
name="test_has_title"

CI/CD will use this as parameters:
pytest -v {classname}.py::{name}

**Comment by mxschmitt** [comment]
We internally parameterise as well: https://github.com/microsoft/playwright-pytest/blob/19659038de3a7d22b55485ddc7535e253881bcef/pytest_playwright/pytest_playwright.py#L88-L91

not sure if we can do much there, Pytest has param id which would allow you to change it but probably it needs to be unique:

https://docs.pytest.org/en/stable/reference/reference.html#pytest-param
