### ISSUE TITLE
[Feature]: Use of pw prefix for all custom pytest options

### ISSUE THREAD

**Issue by DieTapete** [microsoft/playwright-pytest#252]
### 🚀 Feature Request

The custom options added by the playwright pytest plugin are quite generic like `output` and `device` and can easily conflict with other plugins or a user's custom options since pytest does not support proper namespacing. Therefore all playwright options should be prefixed with `pw`. Namely: `pw-output`, `pw-device`, etc.
A non-breaking alternative, would be to allow a user to configure the option names.

### Motivation

It is clearer for the user which options belong specifically to the playwright plugin and other plugins that would otherwise have conflicting option names would now work.

**Comment by Wurstnase** [comment]
Might be a good idea.

I just run into this issue with my own `context`-fixture:
```
ERROR sources/tests/ui/test_home.py::TestDefault::test__home__success_expected - AttributeError: 'dict' object has no attribute 'new_page'
```

**Comment by mxschmitt** [comment]
I'll close it for now since we don't have plans to change the naming of your fixtures (would break too many users, doing it the other way around seems not a big problem - since not many customers have reported issues so far).

**Comment by Wurstnase** [comment]
I would not break any other users. Think about something like this:

```python
@pytest_asyncio.fixture(loop_scope="session")
async def _pw_context(_pw_new_context: CreateContextCallback) -> BrowserContext:
    return await _pw_new_context()

@pytest_asyncio.fixture(loop_scope="session")
async def context(_pw_context: BrowserContext) -> BrowserContext:
    return await _pw_context()
```
