### ISSUE TITLE
pytest django SynchronousOnlyOperation

### ISSUE THREAD

**Issue by PyB1l** [microsoft/playwright-pytest#29]
I am trying the simplest scenario without pytest-playwright plugin.

```
import pytest
from playwright import sync_playwright

@pytest.mark.django_db
def test_p(live_server):
    playwright = sync_playwright().start()
    browser = playwright.chromium.launch()
    page = browser.newPage()
    page.goto(f"{live_server.url}")
    page.close()
```

And I am getting the following error

 **django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.**

**Comment by kumaraditya303** [comment]
@PyB1l, for running Django tests with playwright you need to set environment variable 
`
DJANGO_ALLOW_ASYNC_UNSAFE = "true"
`
This can be done by creating a [conftest.py](https://docs.pytest.org/en/2.1.0/plugins.html#conftest-py-local-per-directory-plugins) in the tests directory and setting the environment variable using 
```py
# conftest.py
import os
os.environ.setdefault("DJANGO_ALLOW_ASYNC_UNSAFE","true")

**Comment by mxschmitt** [comment]
Closed because of inactivity. Feel free to reopen if the solution by @kumaraditya303 does not work.

**Comment by felipe3dfx** [comment]
I have same problem, i use pytest-asyncio and channels with Django, how i can make this works without set environment variable?
Not found docs about this
