### ISSUE TITLE
Safer fixture

### ISSUE THREAD

**Issue by fcollonval** [microsoft/playwright-pytest#31]
Looking at the code of the fixtures, I see that the yield operation is not protected

For example:

https://github.com/microsoft/playwright-pytest/blob/fb5a303999e018b75e006edc0ceb1e4f0b4c67be/pytest_playwright/pytest_playwright.py#L97-L98

I think it should be:

```
try:
    yield pw
finally:
    pw.close()
```

to ensure fixture are closed even if an error occurs within a test.

> This apply to other fixtures as well

**Comment by mxschmitt** [comment]
Did you experience any errors or issues?

**Comment by fcollonval** [comment]
Not with playwright, but I hit that kind of errors with some fixture I made in the past.

I start learning playwright this week-end. So I'm not familiar with the consequence of missing the stop or close methods. But for example, I read that the for video recording it is important to close the browser / context / page.

**Comment by reddypdl** [comment]
if an exception happens during the setup code (before the _yield_ keyword), the teardown code (after the _yield_) will not be called. you should be using **addfinalizer** for cleanup , more info @ https://docs.pytest.org/en/6.2.1/fixture.html?highlight=yield#pytest-fixtures-explicit-modular-scalable

**Comment by pavelfeldman** [comment]
My understanding is that pytest does this for us and it only makes sense to handle exceptions happening before the call to yield.

**Comment by fcollonval** [comment]
Thanks for the info
