### ISSUE TITLE
Record Video?

### ISSUE THREAD

**Issue by quenck** [microsoft/playwright-pytest#35]
Is ist possible to set the option to record a video in the received page instance?
https://playwright.dev/docs/api/class-browser#browsernewcontextoptions

**Comment by mxschmitt** [comment]
Hi yes, you can extend the context options to add the corresponding options to record video like that in your confgtest.py:

```py
import pytest

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "record_video_dir": "./videos"
    }
```

**Comment by quenck** [comment]
thx!

**Comment by 4ydan** [comment]
I have the issue now that all my videos are in one folder with unreadable names when using a custom context like this:
```
@pytest.fixture(scope="session")
def context(
    browser_type: BrowserType,
    browser_type_launch_args: Dict,
    browser_context_args: Dict
):
```
Is there a way to get the nice readable test names back?
