### ISSUE TITLE
How to realize the function of failed redo?

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-pytest#39]
Similar to seliniumbase's --reruns
When a test has a problem, pytest can rerun the script

**Comment by mxschmitt** [comment]
You can use [flaky](https://github.com/box/flaky), does this work for your use-case?

**Comment by zhonghai9967** [comment]
1.try this:
import pytest
from playwright.sync_api import Page

@pytest.mark.flaky(reruns=2)
def test_xinxibiao(page, context):
    my_script...
>pytest my_script.py

2.try this:
from playwright.sync_api import Page

def test_xinxibiao(page, context):
    my_script...
>pytest my_script.py --reruns 2
