### ISSUE TITLE
How to open two pages?

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-pytest#40]
browser = playwright.chromium.launch()
context = browser.new_context()    
page0 = context.new_page()
page = context.new_page()

How to open two pages using pytest?
Thank you！

**Comment by mxschmitt** [comment]
The pytest plugin provides you a default page. A second or additional pages you can create based on the context fixture. Example:

```py
def test_foobar(page, context):
    page2 = context.new_page()
    page.goto("https://example.com")
    page2.goto("https://github.com")
```

**Comment by zhonghai9967** [comment]
thank you！！！

**Comment by kumaraditya303** [comment]
It would be better to have docs about playwright pytest plugin on the docs
website https://playwright.dev/docs/test-runners?_highlight=test with some
examples @mxschmitt

**Comment by snackattas** [comment]
> The pytest plugin provides you a default page. A second or additional pages you can create based on the context fixture. Example:
> 
> ```python
> def test_foobar(page, context):
>     page2 = context.new_page()
>     page.goto("https://example.com")
>     page2.goto("https://github.com")
> ```

Hey, I don't think this strategy works? I just tried that, and both pages had the same cookies...it didn't create different contexts. How would I create 2 pages, compliantly through pytest playwright fixtures, but, do it with different contexts/cookies?
