### ISSUE TITLE
context fixture

### ISSUE THREAD

**Issue by wpeterw** [microsoft/playwright-pytest#44]
Hi,

I'm looking for an example on how to use the context fixture. My goal is to parametrize a test with different devices. Is this possible with the pytest-playwright plugin ?

**Comment by pluckhuang** [comment]
> Hi,
> 
> I'm looking for an example on how to use the context fixture. My goal is to parametrize a test with different devices. Is this possible with the pytest-playwright plugin ?

i know pytest has context fixture，maybe it is you want

**Comment by wpeterw** [comment]
Thanks but I'm looking for an example om how to use this: https://github.com/microsoft/playwright-pytest/blob/76d19c03d2680b87fba059a30119c3f9fe62eadf/pytest_playwright/pytest_playwright.py#L125

**Comment by hampsterx** [comment]
> Function scope: These fixtures are created when requested in a test function and destroyed when the test ends.

> context: New browser context for a test.
> page: New browser page for a test.


yep its easier to manage this yourself.

If you look at that fixture..

```
@pytest.fixture
def context(
    browser: Browser, browser_context_args: Dict
) -> Generator[BrowserContext, None, None]:
    context = browser.new_context(**browser_context_args)
    yield context
    context.close()
```

pretty simple, just need to close context when done so if creating a bunch for a test then need to keep track of em.

This is what I am doing for example..


```

@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "viewport": {"width": 1440, "height": 900},
    }


@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {
        **browser_type_launch_args,
        "slow_mo": 50
    }


@pytest.fixture(scope="function")
def browser_context(request, browser, browser_context_args):
    _contexts = []

    def f(viewport=None):
        args = copy.copy(browser_context_args)
        if viewport:
            args['viewport'] = viewport

        log.debug("Create new context", extra=args)
        _contexts.append(browser.new_context(**args))
        return _contexts[-1]

    def teardown():
        for context in _contexts:
            context.close()

    request.addfinalizer(teardown)
    return f


@pytest.fixture(scope="function")
def desktop_context(browser, browser_context):
    def f():
        return browser_context(viewport={"width": 920, "height": 800})

    return f
```

hope that helps :)

**Comment by wpeterw** [comment]
Thanks for the example. Where do you create the browser ? In conftest.py ?

**Comment by mrudulp** [comment]
you can import Browser Fixture which has session scope, so you dont need to create Browser so to say
