### ISSUE TITLE
Collect xhr and js errors if test failed

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-pytest#49]
Hi!
I use playwright and pytest. But I don't know, if it is possible to collect errors from browser in the case, when test failes?

**Comment by mxschmitt** [comment]
You could add a custom Pytest fixture which fails when the `pageerror` event got fired, see here for the `pageerror` event: https://playwright.dev/python/docs/api/class-page?_highlight=pageerror#pageonpageerror

Regarding xhr/Fetch, depends what you consider there as an error. e.g. a 404 or 5XX. You can add request interception to collect these and fail if one occurs.

**Comment by mxschmitt** [comment]
Closing for now, there is currently some stuff work in progress to debug failing tests easier cross-language wide and on CI too.
