### ISSUE TITLE
[Question] How to make the context with funciton 'launch_persistent_context'

### ISSUE THREAD

**Issue by b3wsh** [microsoft/playwright-pytest#50]
How to make the context with funciton 'launch_persistent_context'? I want to set `user_data_dir` in browser context, How can I do it?

Thanks!

**Comment by mxschmitt** [comment]
You can use a fixture like that, this will make that all the pages inside your test are created from the persistent context:

```py
import pytest
from playwright.sync_api import BrowserType, Playwright
from typing import Dict

@pytest.fixture(scope="session")
def context(
    playwright: Playwright,
    browser_name: str,
    browser_type_launch_args: Dict,
    browser_context_args: Dict
):
    context = getattr(playwright, browser_name).launch_persistent_context("./foobar", **{
        **browser_type_launch_args,
        **browser_context_args,
        "locale": "de-DE",
    })
    yield context
    context.close()
```

**Comment by marklane2001** [comment]
Hi, How is this used within the test please?

**Comment by mxschmitt** [comment]
You can put it into your conftest.py and use it then inside your tests via the context fixture. See for example here: https://www.tutorialspoint.com/pytest/pytest_conftest_py.htm and the readme for examples.

**Comment by marklane2001** [comment]
Worked a treat thanks. The only issue I have that it opens x3 blank browsers before it loads the initial one for the test and I can't work out why. Am I using 'context' correctly in the test?

@pytest.mark.order(1)
def test_sys_admin_login(context, env):
    page = context.new_page()
    home_page = HomePage(page)
    login_page = LoginPage(page)
    login_page.navigate(env)
