### ISSUE TITLE
[FEATURE] Run Browser once in TestClass

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-pytest#60]
Hi!
I have the following code:
```
class TestClass:
    def test_a(self, page):
        print("open site")
        self.page = page
        self.page.goto("https://microsoft.com")
    
    def test_b(self, page):
        print("check title of site")
        self.page = page
        page_title = self.page.title()#
        assert page_title == "Microsoft - Official Home Page"
```
The question is - how can I run browser once for 2 tests? Sequence should be the following - browser is starting, test_a is executing, then test_b is executing, then browser is closing.

**Comment by mxschmitt** [comment]
Currently the test runner is optimised for method based tests: https://docs.pytest.org/en/latest/getting-started.html#create-your-first-test where the best support is given.

We might explore class based testing in the future, will mark it as "p3-collecting-feedback".

**Comment by storenth** [comment]
I suggest to spawn your own browser based `custom_page` or something because of its `session` implementation:
<img width="754" alt="Screenshot 2024-02-19 at 23 35 17" src="https://github.com/microsoft/playwright-pytest/assets/18244131/0b36bfdd-6c6b-43c1-928c-3af5cae245f4">

**Comment by mxschmitt** [comment]
I'll close it for now since this issue seems stale and didn't get enough upvotes in the past. Feel free to re-file if you still encounter issues. We usually recommend functions as tests. Thanks!
