### ISSUE TITLE
video size 0KB on windows 10

### ISSUE THREAD

**Issue by kisscelia** [microsoft/playwright-pytest#75]
command:
pytest -k test_bucket_info --video on --screenshot on -vv -s

when done, video's size is 0KB

![image](https://user-images.githubusercontent.com/13063673/133552531-03d19cd0-3922-4d61-969b-1e2327428e94.png)

and, another question: does the tempfile.TemporaryDirectory works well on windows 10?

thanks.

**Comment by mxschmitt** [comment]
Could you show me the content of your test file? This would help to understand the issue.

> and, another question: does the tempfile.TemporaryDirectory works well on windows 10?

it should, we run our tests also on Windows and they pass there.

**Comment by mxschmitt** [comment]
Closing since it seems stale.
