### ISSUE TITLE
pytest --headed stopped working in 0.2.0

### ISSUE THREAD

**Issue by naro** [microsoft/playwright-pytest#76]
The --headed argument does not open a browser when using pytest-playwright 0.2.0

```
pip install -U pytest-playwright==0.2.0
pytest --headed <test>   # No browser visible
pip install -U pytest-playwright==0.1.0
pytest --headed <test>   # browser is in headed mode
pip install -U pytest-playwright==0.2.0
pytest --headed <test>   # No browser visible
```
Adding 
`launch_args['headless'] = False` in browser_type_launch_args works fine and the browser opens in headed mode even with 0.2.0

**Comment by mxschmitt** [comment]
I tried to produce it but was not able to. Could you share us your pytest output to verify that the correct version of the pytest plugin get picked up? And seeing a test case might also help to track the issue further down.

**Comment by naro** [comment]
Thank you for trying that out. I found the issue is with overriding the `browser_type_launch_args` fixture.

This example fails in a clean environment:
test.py:
```
def test_example_is_working(page):
    page.goto("https://example.com")
    assert page.inner_text('h1') == 'Example Domain'
    page.click("text=More information")
```

conftest.py
```
import pytest 
@pytest.fixture(scope="session")
def browser_type_launch_args():
   return {}
```

but it works with 0.1.0. Is there a way how to override `browser_type_launch_args` safely?

**Comment by mxschmitt** [comment]
Ah this is expected. Since you override and not inherit from it. When you are using something like this it should work:

```py
import pytest 
@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
   return {
      **browser_type_launch_args,
      # custom launch options to override...
    }
```

**Comment by naro** [comment]
Thanks, that helped, of course :)
