### ISSUE TITLE
[BUG] Playwright produces zero-bytes .webm videos

### ISSUE THREAD

**Issue by paunovic** [microsoft/playwright-pytest#81]
**Context:**
- Playwright Version: Version 1.15.0-1631797286000
- Operating System: `ubuntu/bionic64`
- Node.js version: v12.16.1
- Browser: All
- Extra: running inside virtualbox vm, host OS is Windows 10.

**Code Snippet**

```python3
@pytest.fixture(autouse=True)
def browser_context_args(browser_context_args: dict) -> dict:

    browser_context_args = {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        },
        "device_scale_factor": 2,
        "record_video_size": {
            "width": 800,
            "height": 600,
        },
    }

    return browser_context_args
```

**Describe the bug**

I am running Playwright + Python + pytest-playwright with following arguments:

```
pytest --tracing retain-on-failure --screenshot only-on-failure --video retain-on-failure
```

On error, tracing and screenshots are saved fine, however videos come out as zero bytes .webm files.

**Comment by mxschmitt** [comment]
@paunovic sorry for the late reply. Do you have a full example somewhere (e.g. GitHub repo)? I tried to confirm it and reproduce it locally, but for me it seems working as intended.

**Comment by mxschmitt** [comment]
Ohhh good catch! Thats the fix for it: https://github.com/microsoft/playwright-pytest/pull/83. Will release it shortly.

**Comment by paunovic** [comment]
Just for posterity, the bug that I was encountering few weeks ago when I initially opened this issue was different - `TemporaryDirectory` was returning underscore instead of dash at one place in the string for some reason, compared to `video.path()`. Looks like there are few buggy behaviours. Personally I refactored my fixtures away from TemporaryDirectory.

Oh and there's also a typo in temp directory name, `playwight`.
