### ISSUE TITLE
How to reuse authentication state in playwright-pytest?

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-pytest#84]
I've got a post login authentication status，And saved in "d:\abc.json".
How to reuse this authentication status in pytest (login free)?
#========The following are the commands used in repl======
from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=False)
page = browser.new_page()
page.goto(url)
page.fill("#userName1",name);page.fill("#password1",pasd);page.click("#btnLogin")
storage=context.storage_state(path='d:/abc.json')

#In the future, you will not need to log in and open the internal web page directly
context = browser.new_context(storage_state='d:/abc.json')
page =context.new_page()
page.goto(...)

How to use abc.json in pytest？？？Thank you very much
I just learned playwright-python, please give an example of how to use it, thank you!
#for example
def test_xinxibiao(page,context):
page = context.new_page()

**Comment by zhonghai9967** [comment]
@mxschmitt  thank you！
I have seen the example you gave, and I have also created files “conftest.py'in the same directory of the current script.
But how to write the actual script?Can you give me an example again?

#I deal with it like this (actually, "conftest.py" is not used)
from playwright.sync_api import sync_playwright;import pytest
def test_1(playwright):
    browser = playwright.chromium.launch(headless=False)
    context=browser.new_context(storage_state='d:/abc.json')
    page=context.new_page()
    page.goto(url)
#This script can be run. However, it doesn't look like a pytest script,The key is that conftest.py is not used

**Comment by mgaitan** [comment]
I implemented this approach
https://gist.github.com/mgaitan/652d39a7df5076e38239d2ae3f6862ed
