### ISSUE TITLE
Pytest fixture - how can I run the same instance of the page for each (py)test?

### ISSUE THREAD

**Issue by kepler2** [microsoft/playwright-pytest#90]
Hello guys!

**First of all congratulations for the hard work involved in Playwright!**

I know this is not really an "issue" but I'll try my luck here guys.

How can you setup a page instance in which all the tests are run in the same page? Using Playwright / Pytest.

**For example:**

1 - Open https://en.wikipedia.org/wiki/Main_Page

2 - Check that Search field is visible

3 - Check that the logo is displayed

... but all without reopening the browser for each test!

I have checked the **[documentation](https://playwright.dev/python/docs/test-runners)** but still I can't find how to do it.

Note that I'm a beginner.

Thanks!

**Comment by mxschmitt** [comment]
This is not recommended, since then one test can cause another test to fail. Thats why we have context isolation (which gives you a new page instance for every test) by default.

If you still want to do it, you can override the context/page fixture so it has a session scope:

conftest.py
```python
import pytest
from playwright.sync_api import Browser, BrowserContext
from typing import Dict
@pytest.fixture(scope="session")
def context(
    browser: Browser,
    browser_context_args: Dict
):
    context = browser.new_context(**{
        **browser_context_args,
    })
    yield context
    context.close()
@pytest.fixture(scope="session")
def page(
    context: BrowserContext,
):
    page = context.new_page()
    yield page
```

```python
def test_a(page):
    page.goto("data:text/html,<div>B</div>")
    assert page.text_content("div") == "B"
def test_b(page):
    assert page.text_content("div") == "B"
```
