### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by mattalexx** [microsoft/playwright-pytest#91]
https://playwright.dev/python/docs/test-runners/

**Comment by mxschmitt** [comment]
Did you discover this on pypi or on GitHub? On GitHub its fixed and should be fixed on Pypi with the next release.

**Comment by mattalexx** [comment]
I was referring to the Github setting:

![Screenshot](https://i.imgur.com/WvEyXYh.png)

**Comment by mxschmitt** [comment]
Thanks! Fixed and closing by that.
