### ISSUE TITLE
[BUG] Running PyTest in a low version of PyTest may lead to errors “AttributeError: module 'pytest' has no attribute 'FixtureRequest'“

### ISSUE THREAD

**Issue by jackgithubtest** [microsoft/playwright-pytest#93]
```
@pytest.fixture
def context(
    browser: Browser,
    browser_context_args: Dict,
    pytestconfig: Any,
    request: pytest.FixtureRequest,
) -> Generator[BrowserContext, None, None]:
    pages: List[Page] = []
    context = browser.new_context(**browser_context_args)
    context.on("page", lambda page: pages.append(page))

    tracing_option = pytestconfig.getoption("--tracing")
    capture_trace = tracing_option in ["on", "retain-on-failure"]
    if capture_trace:
        context.tracing.start(
            name=slugify(request.node.nodeid),
            screenshots=True,
            snapshots=True,
        )
def _build_artifact_test_folder(
    pytestconfig: Any, request: pytest.FixtureRequest, folder_or_file_name: str
) -> str:
    output_dir = pytestconfig.getoption("--output")
    return os.path.join(output_dir, slugify(request.node.nodeid), folder_or_file_name)
```
In python3.9+,pytest no longer exists ‘FixtureRequest’
If the ‘FixtureRequest’ is changed to ‘fixture’, it is used normally

**Comment by mxschmitt** [comment]
Which pytest version are you using?

**Comment by jackgithubtest** [comment]
> 您使用的是哪个 pytest 版本？
Sorry, it's the lower version of Pytest
5.4.2

**Comment by jackgithubtest** [comment]
Fixtures, rather than FixtureRequest, are used to accommodate problems caused by lower versions of PyTest

**Comment by jackgithubtest** [comment]
> 
Yes, there are still more 6.0+ now, but I still use the 5.x version due to the historical project, maybe it is just me?

**Comment by jackgithubtest** [comment]
> 是的，我更喜欢只支持pytest 6+，因为5.4.2也快2岁了。我们可以在setup.py中将其设置为最低版本，但到目前为止没有人抱怨。是什么阻止您升级？
Yes, it can be done, but if there is a low version, it can not be used well, maybe it would be a good choice to solve it, THE PR I submitted did not pass, I do not have a MAC, so I can not debug, I think the reason is the prompt connect TimeOut

**Comment by mxschmitt** [comment]
Closing since pytest 6+ is required. There were no other reports in the past years.
